Assignment 1 - Working with NumPy


Objective Understand the basics of NumPy, array creation, and manipulation.


Instructions 


Step 1 Install NumPy using
pip install numpy


Step 2 Create a new Python script numpy_assignment.ipynb. Import NumPy and follow these steps:  


1. Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:  
  a. Calculate the sum, mean, median, and standard deviation of the elements in the array.  
  b. Find the indices of elements greater than 10 in the array.  


2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  
  a. Print the array.  
  b. Find the transpose of the array.  
  c. Calculate the row-wise and column-wise sums of the array.  


3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
  a. Perform element-wise addition, subtraction, and multiplication.  
  b. Compute the dot product of the two arrays.  


4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.  




In [1]:
#import numy library as set alias
import numpy as np

# 1. Create a 1D NumPy array with integers from 1 to 20

In [2]:
arr_1d = np.arange(1, 21)
print("1D Array:\n", arr_1d)

1D Array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


* np.arange(1, 21) creates an array of integers from 1 to 20 (end value 21 is exclusive).

### a. Calculate the sum, mean, median, and standard deviation

In [3]:
sum_arr = np.sum(arr_1d)
mean_arr = np.mean(arr_1d)
median_arr = np.median(arr_1d)
std_arr = np.std(arr_1d)

In [4]:
print("\nArray Statistics:")
print(f"Sum: {sum_arr}")
print(f"Mean: {mean_arr}")
print(f"Median: {median_arr}")
print(f"Standard Deviation: {std_arr}")



Array Statistics:
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


* np.sum() → Adds up all elements

* np.mean() → Calculates the arithmetic mean

* np.median() → Finds the median value

* np.std() → Computes the standard deviation

### b. Find the indices of elements greater than 10

In [5]:
indices_gt_10 = np.where(arr_1d > 10)

In [6]:
print("\nIndices of elements greater than 10:", indices_gt_10)


Indices of elements greater than 10: (array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64),)


* np.where(condition) returns the indices of array elements where the condition is True.

* Here, it finds all positions where values are greater than 10. 

In [7]:
print("Elements greater than 10:", arr_1d[indices_gt_10])

Elements greater than 10: [11 12 13 14 15 16 17 18 19 20]


* arr_1d[indices_gt_10] retrieves those actual elements.

# 2. Create 2D NumPy array of shape 4X4 with numbers ranging from 1 to 16.

In [8]:
arr_2d = np.arange(1, 17).reshape(4,4)

* np.arange(1, 17).reshape(4,4) → Creates values from 1 to 16 and Converts the 1D array into a 4×4 (2D) matrix.

### a. Print the array.  

In [9]:
print("2D Array:\n", arr_2d)

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### b. Transpose of the Array

In [10]:
transpose_arr = arr_2d.T
print("\nTranspose of Array:\n", transpose_arr)


Transpose of Array:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


* .T gives the transpose, i.e., swaps rows and columns.

### c. Calculate the row-wise and column-wise sums of the array.

In [11]:
row_sums = np.sum(arr_2d, axis=1)
col_sums = np.sum(arr_2d, axis=0)
print("\nRow-wise sums:", row_sums)
print("Column-wise sums:", col_sums)


Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]


* axis=1 → Operates horizontally (row-wise).
* axis=0 → Operates vertically (column-wise).
* NumPy uses the axis parameter to define the direction of the operation.

# 3. Create two 3 X 3 arrays filled with random integers between 1 and 20.

In [12]:
arr_3dA = np.random.randint(1, 21, size=(3, 3))
arr_3dB = np.random.randint(1, 21, size=(3, 3))

In [13]:
print("\nArray A:\n", arr_3dA)
print("Array B:\n", arr_3dB)


Array A:
 [[15  1 11]
 [ 9 17  3]
 [10 17 15]]
Array B:
 [[11 18  1]
 [ 9 15 14]
 [11 15  9]]


* np.random.randint(1, 21, size=(3, 3)) creates a 3×3 array filled with random integers between 1 and 20.

* Each run it will produce different random values.

### a. Perform element-wise addition, subtraction, and multiplication.

In [14]:
add_result = arr_3dA + arr_3dB
sub_result = arr_3dA - arr_3dB
mul_result = arr_3dA * arr_3dB

print("\nElement-wise Addition:\n", add_result)
print("\nElement-wise Subtraction:\n", sub_result)
print("\nElement-wise Multiplication:\n", mul_result)


Element-wise Addition:
 [[26 19 12]
 [18 32 17]
 [21 32 24]]

Element-wise Subtraction:
 [[  4 -17  10]
 [  0   2 -11]
 [ -1   2   6]]

Element-wise Multiplication:
 [[165  18  11]
 [ 81 255  42]
 [110 255 135]]


*  NumPy supports vectorized operations, meaning arithmetic is done element-by-element automatically:

* arr_a + arr_b adds each corresponding element.

* arr_a - arr_b subtracts them.

* arr_a * arr_b multiplies them element-wise (not matrix multiplication).

### b. Compute the dot product of the two arrays.

In [15]:
dot_product = np.dot(arr_3dA, arr_3dB)
print("\nDot Product of A and B:\n", dot_product)


Dot Product of A and B:
 [[295 450 128]
 [285 462 274]
 [428 660 383]]


* np.dot() performs matrix multiplication (sum of products of rows and columns).

* This is different from element-wise multiplication — it’s a linear algebra operation.

# Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns.

In [16]:
arr_reshaped = np.arange(1, 13).reshape(3, 4)
print("\nReshaped 3x4 Array:\n", arr_reshaped)


Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


* np.arange(1, 13) .reshape(3, 4)  creates values from 1 to 12 and converts  a 3×4 matrix.

In [17]:
sliced_arr = arr_reshaped[:2, -2:]
print("\nSliced Array (first 2 rows, last 2 columns):\n", sliced_arr)


Sliced Array (first 2 rows, last 2 columns):
 [[3 4]
 [7 8]]


* [:2, -2:] uses slicing:

* :2 → Selects first 2 rows (index 0 and 1).

* -2: → Selects last 2 columns.